# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
# Dummy certificates and private keys used for local testing.
paths-ignore:
  - "config/certificates/**"
