# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  "README.md",
  "DEVELOPMENT.md",
  ".gommitlint.yaml",
  "renovate.json",
  "config/certificates/README.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Digg - Agency for Digital Government"
SPDX-License-Identifier = "CC0-1.0"
