# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
# SPDX-License-Identifier: CC0-1.0

apiVersion: v1
kind: Namespace
metadata:
  name: wallet-ecosystem-local
  labels:
    istio-injection: enabled
