# SPDX-FileCopyrightText: 2025 diggsweden/wallet-ecosystem
#
# SPDX-License-Identifier: CC0-1.0

# This is a basic workflow that is manually triggered

name: Sandbox Test workflow

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      sandbox-url:
        description: 'Sandbox URL'
        default: 'https://example.com'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        java-version: ["21"]
        os: [ubuntu-latest]

    steps:
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Run tests on sandbox
        env:
          MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --errors --fail-at-end -Dstyle.color=always -DinstallAtEnd=true -DdeployAtEnd=true
          GITHUB_ACTOR: ${{ github.actor }}
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SANDBOX_URL: ${{ secrets.SANDBOX_URL }}
          DIGG_WALLET_ECOSYSTEM_VERIFIER_AUDIENCE: x509_san_dns:${SANDBOX_URL}
          DIGG_WALLET_ECOSYSTEM_VERIFIER_FRONTEND_BASE_URI: https://${SANDBOX_URL}/demo-verifier
          DIGG_WALLET_ECOSYSTEM_VERIFIER_BACKEND_BASE_URI: https://${SANDBOX_URL}/verifier
          DIGG_WALLET_ECOSYSTEM_WALLET_CLIENT_GATEWAY_BASE_URI: https://${SANDBOX_URL}/api
          DIGG_WALLET_ECOSYSTEM_WALLET_CLIENT_GATEWAY_API_KEY: my_secret_key
          DIGG_WALLET_ECOSYSTEM_WALLET_PROVIDER_BASE_URI: https://${SANDBOX_URL}/wallet-provider
          DIGG_WALLET_ECOSYSTEM_PID_ISSUER_BASE_URI: https://${SANDBOX_URL}/pid-issuer
          DIGG_WALLET_ECOSYSTEM_KEYCLOAK_BASE_URI: https://${SANDBOX_URL}/idp
          DIGG_WALLET_ECOSYSTEM_SKIP_TESTS_USING_CUSTOM_HOSTS: true
          DIGG_WALLET_ECOSYSTEM_SKIP_TESTS_FOR_KEYCLOAK_HEALTH: true
          DIGG_WALLET_ECOSYSTEM_SKIP_TESTS_FOR_VERIFIER_BACKEND_HEALTH: true
        run: |
          echo "Hello ${{ inputs.sandbox-url }}"
          echo "Sandbox URL value is " "$SANDBOX_URL"
          # shellcheck disable=SC2086
          mvn $MAVEN_CLI_OPTS test
